services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: desafio
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data 

  backend:
    image: luoliveira/desafio-back:latest
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    image: luoliveira/desafio-front:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: {}